import { ROLES, ROLE_VALUES } from './roles.js';
import { PROJECT_STATUS, PROJECT_STATUS_VALUES } from './projectStatus.js';
import { TASK_STATUS, TASK_STATUS_VALUES } from './taskStatus.js';
import { TASK_PRIORITY, TASK_PRIORITY_VALUES } from './taskPriority.js';
import { NOTIFICATION_TYPE, NOTIFICATION_CHANNEL, NOTIFICATION_STATUS } from './notificationTypes.js';

export {
  ROLES,
  ROLE_VALUES,
  PROJECT_STATUS,
  PROJECT_STATUS_VALUES,
  TASK_STATUS,
  TASK_STATUS_VALUES,
  TASK_PRIORITY,
  TASK_PRIORITY_VALUES,
  NOTIFICATION_TYPE,
  NOTIFICATION_CHANNEL,
  NOTIFICATION_STATUS
};

export default {
  ROLES,
  ROLE_VALUES,
  PROJECT_STATUS,
  PROJECT_STATUS_VALUES,
  TASK_STATUS,
  TASK_STATUS_VALUES,
  TASK_PRIORITY,
  TASK_PRIORITY_VALUES,
  NOTIFICATION_TYPE,
  NOTIFICATION_CHANNEL,
  NOTIFICATION_STATUS
};
