export const NOTIFICATION_TYPE = {
  TASK_ASSIGNED: 'TASK_ASSIGNED',
  TASK_REASSIGNED: 'TASK_REASSIGNED',
  TASK_DUE_TOMORROW: 'TASK_DUE_TOMORROW',
  TASK_OVERDUE: 'TASK_OVERDUE',
  PROJECT_DEADLINE_APPROACHING: 'PROJECT_DEADLINE_APPROACHING'
};

export const NOTIFICATION_CHANNEL = {
  EMAIL: 'EMAIL',
  WEB: 'WEB',
  BROWSER: 'BROWSER'
};

export const NOTIFICATION_STATUS = {
  SENT: 'SENT',
  FAILED: 'FAILED',
  READ: 'READ'
};

export default {
  NOTIFICATION_TYPE,
  NOTIFICATION_CHANNEL,
  NOTIFICATION_STATUS
};
