import { useConfirm } from '../context/ConfirmationContext';
import { useState } from 'react';
import { Link, useSearchParams } from 'react-router-dom';
import { Plus, LayoutGrid, List } from 'lucide-react';
import { useAuth } from '../context/AuthContext';
import { apiRequest } from '../services/api';
import useRemote from '../hooks/useRemote';
import { PageHeader, Metrics, LoadState, Badge, Progress } from '../components/planning/PlanningUI';
import ProjectDialog from '../components/planning/ProjectDialog';
import { projectStatuses, prettyDate } from '../utils/planning';
export default function Projects(){
  const confirm = useConfirm();
  const {hasPermission}=useAuth();const [query]=useSearchParams();
  const {data:projects=[],loading,error,reload}=useRemote('/projects');
  const [filters,setFilters]=useState({search:'',status:'',sort:'newest'}),[view,setView]=useState('grid'),[dialog,setDialog]=useState(query.get('create')&&hasPermission('projects.create')?{}:null);
  const [notice,setNotice]=useState(''),[actionError,setActionError]=useState(''),[busy,setBusy]=useState(null),[page,setPage]=useState(1);
  const all=projects||[];
  const filtered=all.filter(project=>(!filters.status||project.status===filters.status)&&(!filters.search||[project.name,project.description,project.owner_name].some(value=>value?.toLowerCase().includes(filters.search.toLowerCase())))).sort((a,b)=>filters.sort==='name'?a.name.localeCompare(b.name):filters.sort==='due'?(a.end_date||'9999').localeCompare(b.end_date||'9999'):filters.sort==='progress'?(b.progress||0)-(a.progress||0):b.id-a.id);
  const change=(key,value)=>{setFilters(previous=>({...previous,[key]:value}));setPage(1);};
  const remove=async project=>{if(!await confirm({title:'Delete project?',description:'Deleting "'+project.name+'" will permanently delete the project and all its tasks. This cannot be undone.',confirmLabel:'Delete project'}))return;setBusy(project.id);setActionError('');try{await apiRequest('/projects/'+project.id,{method:'DELETE'});setNotice('Project deleted.');reload();}catch(err){setActionError(err.message);}finally{setBusy(null);}};
  const actions=project=><div className="management-actions">{hasPermission('tasks.view')&&<Link className="planning-text-link" to={'/tasks?project_id='+project.id}>Tasks</Link>}{hasPermission('team.view')&&<Link className="planning-text-link" to={'/team?project_id='+project.id}>Team</Link>}{hasPermission('projects.edit')&&<button className="management-button secondary" disabled={busy!==null} onClick={()=>setDialog(project)}>Edit</button>}{hasPermission('projects.delete')&&<button className="management-button danger" disabled={busy!==null} onClick={()=>remove(project)}>Delete</button>}</div>;
  return <div className="planning-page"><PageHeader title="Projects" description="A clear view of delivery, ownership and project health.">{hasPermission('projects.create')&&<button className="management-button" onClick={()=>setDialog({})}><Plus size={15}/> New project</button>}</PageHeader>
    <Metrics items={[{label:'Accessible projects',value:all.length},{label:'In progress',value:all.filter(project=>project.status==='In Progress').length},{label:'Completed',value:all.filter(project=>project.status==='Completed').length,tone:'success'},{label:'With overdue work',value:hasPermission('tasks.view')?all.filter(project=>project.overdue_tasks>0).length:null,tone:'danger'}]}/>
    {notice&&<div className="management-notice" role="status">{notice}</div>}{actionError&&<div className="management-notice error" role="alert">{actionError}</div>}
    <div className="management-toolbar"><input type="search" aria-label="Search projects" placeholder="Search project, description or owner…" value={filters.search} onChange={event=>change('search',event.target.value)}/><select aria-label="Filter project status" value={filters.status} onChange={event=>change('status',event.target.value)}><option value="">All statuses</option>{projectStatuses.map(value=><option key={value}>{value}</option>)}</select><select aria-label="Sort projects" value={filters.sort} onChange={event=>change('sort',event.target.value)}><option value="newest">Newest first</option><option value="name">Name A–Z</option><option value="due">Earliest end date</option>{hasPermission('tasks.view')&&<option value="progress">Highest task completion</option>}</select><button className="management-button secondary" aria-pressed={view==='grid'} onClick={()=>setView('grid')}><LayoutGrid size={14}/> Cards</button><button className="management-button secondary" aria-pressed={view==='list'} onClick={()=>setView('list')}><List size={14}/> List</button><button className="management-button secondary" onClick={reload}>Refresh</button></div>
    <LoadState loading={loading} error={error} onRetry={reload} empty={!filtered.length}>
      {view==='grid'?<div className="planning-project-grid">{filtered.slice((page-1)*12,page*12).map(project=><article className="planning-project-card" key={project.id}><div className="planning-inline"><Badge value={project.status}/>{project.overdue_tasks>0&&<Badge value="Overdue"/>}</div><h2><Link to={'/projects/'+project.id}>{project.name}</Link></h2><p>{project.description||'No description provided.'}</p><Progress value={project.progress}/><div className="planning-muted" style={{fontSize:11,marginBottom:15}}>{project.total_tasks==null?'Task counts restricted':project.completed_tasks+' of '+project.total_tasks+' tasks complete'} · {Number(project.member_count)+1} people</div><div className="planning-project-footer"><span>{project.owner_name}</span><span>{prettyDate(project.end_date)}</span></div><div style={{marginTop:15}}>{actions(project)}</div></article>)}</div>:<div className="management-table-wrap"><table className="management-table"><thead><tr><th>Project</th><th>Owner</th><th>Status</th><th>Task completion</th><th>Target date</th><th>Actions</th></tr></thead><tbody>{filtered.slice((page-1)*12,page*12).map(project=><tr key={project.id}><td><Link className="planning-item-title" to={'/projects/'+project.id}>{project.name}</Link><small>{Number(project.member_count)+1} people</small></td><td>{project.owner_name}</td><td><Badge value={project.status}/></td><td><Progress value={project.progress}/></td><td>{prettyDate(project.end_date)}{project.overdue_tasks>0&&<small>{project.overdue_tasks} overdue tasks</small>}</td><td>{actions(project)}</td></tr>)}</tbody></table></div>}
      <div className="management-pagination"><span className="planning-muted">{filtered.length} projects · Page {page} of {Math.max(1,Math.ceil(filtered.length/12))}</span><div className="management-actions"><button className="management-button secondary" disabled={page===1} onClick={()=>setPage(value=>value-1)}>Previous</button><button className="management-button secondary" disabled={page*12>=filtered.length} onClick={()=>setPage(value=>value+1)}>Next</button></div></div>
    </LoadState>
    {dialog&&<ProjectDialog project={dialog.id?dialog:null} onClose={()=>setDialog(null)} onSaved={()=>{setDialog(null);setNotice('Project saved.');reload();}}/>}
  </div>;
}
