const router = require('express').Router();
const authenticate = require('../middleware/authMiddleware');
const { authorizeRoles, requirePermission } = require('../middleware/rbacMiddleware');
const controller = require('../controllers/adminController');
const { bodyFields } = require('../middleware/inputValidation');
router.use(authenticate, authorizeRoles('super_admin', 'admin'));
router.get('/roles', requirePermission('users.view'), controller.getRoles);
router.put('/roles/:role', requirePermission('roles.manage'), bodyFields('permissions','version'), controller.updateRolePolicy);
router.get('/users', requirePermission('users.view'), controller.getUsers);
router.post('/users', requirePermission('users.create'), bodyFields('full_name','email','password','role','department','job_title'), controller.createUser);
router.get('/users/:id', requirePermission('users.view'), controller.getUserById);
router.put('/users/:id', requirePermission('users.edit'), bodyFields('full_name','email','department','job_title'), controller.updateUser);
router.patch('/users/:id/role', requirePermission('users.roles'), bodyFields('role'), controller.updateUserRole);
router.patch('/users/:id/status', requirePermission('users.status'), bodyFields('is_active'), controller.updateUserStatus);
router.put('/users/:id/permissions', requirePermission('users.roles'), bodyFields('overrides'), controller.updateUserPermissions);
router.get('/stats', requirePermission('users.view'), controller.getSystemStats);
router.get('/audit-logs', requirePermission('audit.view'), controller.getAuditLogs);
module.exports = router;
