const router = require('express').Router();
const authenticate = require('../middleware/authMiddleware');
const { authorizeRoles, requirePermission } = require('../middleware/rbacMiddleware');
const controller = require('../controllers/adminController');
router.use(authenticate, authorizeRoles('super_admin', 'admin'));
router.get('/roles', requirePermission('users.view'), controller.getRoles);
router.put('/roles/:role', requirePermission('roles.manage'), controller.updateRolePolicy);
router.get('/users', requirePermission('users.view'), controller.getUsers);
router.post('/users', requirePermission('users.create'), controller.createUser);
router.get('/users/:id', requirePermission('users.view'), controller.getUserById);
router.put('/users/:id', requirePermission('users.edit'), controller.updateUser);
router.patch('/users/:id/role', requirePermission('users.roles'), controller.updateUserRole);
router.patch('/users/:id/status', requirePermission('users.status'), controller.updateUserStatus);
router.put('/users/:id/permissions', requirePermission('users.roles'), controller.updateUserPermissions);
router.get('/stats', requirePermission('users.view'), controller.getSystemStats);
router.get('/audit-logs', requirePermission('audit.view'), controller.getAuditLogs);
module.exports = router;
