const {test,mock}=require('node:test'),assert=require('node:assert/strict');
const {pool,request,ids,createTask}=require('../helpers/fixtures');
const push=require('../../services/mobilePushService');
const {runReminders}=require('../../jobs/taskReminderJob');
const {todayInZone,shiftDay}=require('../../utils/notificationDates');
const gateway=mock.method(push,'postExpo',async(endpoint,body)=>endpoint==='send'?body.map(()=>({status:'ok',id:require('crypto').randomUUID()})):{});
const token='ExpoPushToken[test-device]';
test('device registration authenticates, validates, binds current user and removes only owned tokens',async()=>{
 assert.equal((await request(null,'/notifications/push-devices','POST',{token,platform:'android'})).status,401);
 assert.equal((await request('member','/notifications/push-devices','POST',{token,platform:'android'})).status,503);
 process.env.PUSH_ENABLED='true';
 for(const body of [{token:'bad',platform:'android'},{token,platform:'desktop'},{token,platform:'android',user_id:ids.admin}])assert.equal((await request('member','/notifications/push-devices','POST',body)).status,400);
 assert.equal((await request('member','/notifications/push-devices','POST',{token,platform:'android'})).status,200);
 await request('admin','/notifications/push-devices','DELETE',{token});
 assert.equal((await pool.execute('SELECT user_id FROM mobile_push_devices WHERE expo_token=?',[token]))[0][0].user_id,ids.member);
 await request('viewer','/notifications/push-devices','POST',{token,platform:'android'});
 assert.equal((await pool.execute('SELECT user_id FROM mobile_push_devices WHERE expo_token=?',[token]))[0][0].user_id,ids.viewer);
 await request('viewer','/notifications/push-devices','DELETE',{token});
 assert.equal((await pool.execute('SELECT id FROM mobile_push_devices WHERE expo_token=?',[token]))[0].length,0);
});
test('tomorrow push respects preference, scope, completion, expiry and concurrent daily deduplication',async()=>{
 const tomorrow=shiftDay(todayInZone(process.env.APP_TIMEZONE||'Asia/Kolkata'),1);
 await request('member','/notifications/push-devices','POST',{token,platform:'android'});
 const due=await createTask(1,{name:'Tomorrow push',assigned_to:ids.member,due_date:tomorrow});
 const done=await createTask(1,{status:'Completed',assigned_to:ids.member,due_date:tomorrow});
 const unrelated=await createTask(2,{assigned_to:ids.member,due_date:tomorrow});
 const overdue=await createTask(1,{assigned_to:ids.member,due_date:'2020-01-01'});
 await runReminders();assert.equal(gateway.mock.callCount(),0);
 assert.equal((await request('member','/notifications/preferences','PUT',{push_due_tomorrow:true})).status,200);
 await Promise.all([runReminders(),runReminders(),runReminders()]);
 assert.equal(gateway.mock.callCount(),1);
 const sent=gateway.mock.calls[0].arguments[1][0];assert.equal(sent.to,token);assert.equal(sent.channelId,'task-reminders');assert.equal(sent.data.taskId,due);assert.equal(sent.data.userId,ids.member);assert.ok(!sent.body.includes('Tomorrow push'));
 const [logs]=await pool.execute("SELECT * FROM notification_logs WHERE channel='PUSH'");assert.equal(logs.length,1);assert.equal(logs[0].status,'ACCEPTED');assert.ok(![done,unrelated,overdue].includes(logs[0].task_id));
 await request('member','/notifications/push-devices','DELETE',{token});
 await request('member','/notifications/push-devices','POST',{token,platform:'android'});
 await runReminders();assert.equal(gateway.mock.callCount(),1);
 await createTask(1,{assigned_to:ids.member,due_date:tomorrow});
 await pool.execute('UPDATE mobile_push_devices SET expires_at=DATE_SUB(NOW(),INTERVAL 1 DAY)');await runReminders();assert.equal(gateway.mock.callCount(),1);
});
test('push failure is isolated, invalid devices are removed and receipts distinguish accepted from sent',async()=>{
 await request('member','/notifications/push-devices','POST',{token,platform:'android'});
 gateway.mock.mockImplementation(async()=>{throw new Error('Provider failed with secret');});
 const due=await createTask(1,{assigned_to:ids.member,due_date:shiftDay(todayInZone(process.env.APP_TIMEZONE||'Asia/Kolkata'),1)});
 await assert.doesNotReject(runReminders());
 const [failed]=await pool.execute("SELECT * FROM notification_logs WHERE task_id=? AND channel='PUSH'",[due]);assert.equal(failed[0].status,'FAILED');assert.equal(failed[0].error_message,'PUSH_DELIVERY_FAILED');
 gateway.mock.mockImplementation(async()=>[{status:'error',details:{error:'DeviceNotRegistered'}}]);
 await createTask(1,{assigned_to:ids.member,due_date:shiftDay(todayInZone(process.env.APP_TIMEZONE||'Asia/Kolkata'),1)});
 await runReminders();assert.equal((await pool.execute('SELECT id FROM mobile_push_devices WHERE expo_token=?',[token]))[0].length,0);
 const [receiptRows]=await pool.execute('SELECT * FROM mobile_push_receipts');assert.equal(receiptRows.length,1);
 await pool.execute('UPDATE mobile_push_receipts SET created_at=DATE_SUB(NOW(),INTERVAL 20 MINUTE)');
 gateway.mock.mockImplementation(async()=>({[receiptRows[0].ticket_id]:{status:'ok'}}));await push.checkReceipts();
 assert.equal((await pool.execute('SELECT status FROM notification_logs WHERE id=?',[receiptRows[0].log_id]))[0][0].status,'SENT');
});
test('failed receipts remove only the affected current device and never leak provider messages',async()=>{
 await request('member','/notifications/push-devices','POST',{token,platform:'android'});
 gateway.mock.mockImplementation(async()=>[{status:'ok',id:'receipt-failure'}]);
 await createTask(1,{assigned_to:ids.member,due_date:shiftDay(todayInZone(process.env.APP_TIMEZONE||'Asia/Kolkata'),1)});await runReminders();
 await pool.execute('UPDATE mobile_push_receipts SET created_at=DATE_SUB(NOW(),INTERVAL 20 MINUTE) WHERE ticket_id=?',['receipt-failure']);
 gateway.mock.mockImplementation(async()=>({'receipt-failure':{status:'error',message:'secret',details:{error:'DeviceNotRegistered'}}}));await push.checkReceipts();
 const [rows]=await pool.execute("SELECT l.status,l.error_message FROM notification_logs l JOIN mobile_push_receipts r ON r.log_id=l.id WHERE r.ticket_id='receipt-failure'");assert.equal(rows[0].status,'FAILED');assert.equal(rows[0].error_message,'DeviceNotRegistered');assert.equal((await pool.execute('SELECT id FROM mobile_push_devices WHERE expo_token=?',[token]))[0].length,0);
});
