const {test}=require('node:test');
const assert=require('node:assert/strict');
const {pool,ids,request,tokenFor,getBase,jwt,catalog,resolveAccess,canManageAccount,validatePermissions}=require('../helpers/fixtures');
const {redact}=require('../../models/auditModel');

test('personal reminders validate time zones, remain private and support edit/dismiss/delete', async () => {
  const instant=new Date(Date.now()+3600000);
  const local=new Date(instant.getTime()+330*60000).toISOString().slice(0,19)+'+05:30';
  const created=await request('member','/reminders','POST',{title:'Personal follow-up',notes:'Review the brief',remind_at:local});
  assert.equal(created.status,201);
  assert.equal(created.data.data.remind_at,instant.toISOString().slice(0,19)+'Z');
  const id=created.data.data.id;
  assert.equal((await request('admin','/reminders')).data.data.length,0);
  assert.equal((await request('admin','/reminders/'+id,'PUT',{status:'dismissed'})).status,404);
  assert.equal((await request('admin','/reminders/'+id,'DELETE')).status,404);
  assert.equal((await request('member','/reminders','POST',{title:'Past',remind_at:new Date(Date.now()-60000).toISOString()})).status,400);
  assert.equal((await request('member','/reminders','POST',{title:'No timezone',remind_at:'2029-01-01T09:00'})).status,400);
  const [restricted]=await pool.execute("INSERT INTO tasks (project_id,user_id,created_by,name) VALUES (2,?,?,'Private work')",[ids.admin,ids.admin]);
  assert.equal((await request('member','/reminders','POST',{title:'Forbidden link',task_id:restricted.insertId,remind_at:instant.toISOString()})).status,403);
  assert.equal((await request('member','/reminders/'+id,'PUT',{title:'Updated follow-up',remind_at:instant.toISOString(),status:'invalid'})).status,400);
  assert.equal((await request('member','/reminders/'+id,'PUT',{title:'Updated follow-up',remind_at:instant.toISOString()})).status,200);
  assert.equal((await request('member','/reminders/'+id,'PUT',{status:'dismissed'})).data.data.status,'dismissed');
  assert.equal((await request('member','/reminders/'+id,'DELETE')).status,200);
  assert.equal((await request('member','/reminders')).data.data.length,0);
});
test('concurrent reminder delivery creates one notification and skips completed or inaccessible tasks', async () => {
  await pool.execute("UPDATE tasks SET status='Completed' WHERE id=1");
  const [linked]=await pool.execute("INSERT INTO tasks (project_id,created_by,name) VALUES (1,?,'Revoked work')",[ids.project_manager]);
  const {dispatchPersonalReminders}=require('../../jobs/personalReminderJob');
  const future=new Date(Date.now()+3600000).toISOString();
  const personal=await request('member','/reminders','POST',{title:'Deliver once',remind_at:future});
  const completed=await request('member','/reminders','POST',{title:'Completed task',task_id:1,remind_at:future});
  const revoked=await request('viewer','/reminders','POST',{title:'Revoked task access',task_id:linked.insertId,remind_at:future});
  assert.equal(personal.status,201);assert.equal(completed.status,201);assert.equal(revoked.status,201);
  await request('admin','/admin/users/'+ids.viewer+'/permissions','PUT',{overrides:{'tasks.view':false}});
  await pool.query("UPDATE reminders SET remind_at = UTC_TIMESTAMP() - INTERVAL 1 MINUTE WHERE status = 'scheduled'");
  const counts=await Promise.all([dispatchPersonalReminders(),dispatchPersonalReminders(),dispatchPersonalReminders()]);
  assert.equal(counts.reduce((sum,count)=>sum+count,0),1);
  const [notifications]=await pool.query("SELECT * FROM notifications WHERE type = 'PERSONAL_REMINDER'");
  assert.equal(notifications.length,1);assert.equal(notifications[0].title,'Deliver once');
  const list=await request('member','/reminders');
  assert.equal(list.data.data.find(item=>item.id===personal.data.data.id).status,'sent');
  assert.equal(list.data.data.find(item=>item.id===completed.data.data.id).status,'dismissed');
  assert.equal((await request('viewer','/reminders')).data.data[0].status,'dismissed');
  assert.equal(await dispatchPersonalReminders(),0);
  await request('admin','/admin/users/'+ids.viewer+'/permissions','PUT',{overrides:null});
});

test('inactive accounts do not receive personal notifications until reactivated', async () => {
  const {dispatchPersonalReminders}=require('../../jobs/personalReminderJob');
  const created=await request('viewer','/reminders','POST',{title:'Paused while inactive',notes:'Private reminder content',remind_at:new Date(Date.now()+3600000).toISOString()});
  assert.equal(created.status,201);
  const [audits]=await pool.execute("SELECT details FROM audit_logs WHERE action = 'REMINDER_CREATED' AND resource_id = ?",[created.data.data.id]);
  assert.equal(audits[0].details.includes('Private reminder content'),false);
  assert.equal(audits[0].details.includes('Paused while inactive'),false);
  await pool.execute('UPDATE users SET is_active = 0 WHERE id = ?',[ids.viewer]);
  await pool.execute('UPDATE reminders SET remind_at = UTC_TIMESTAMP() - INTERVAL 1 MINUTE WHERE id = ?',[created.data.data.id]);
  assert.equal(await dispatchPersonalReminders(),0);
  await pool.execute('UPDATE users SET is_active = 1 WHERE id = ?',[ids.viewer]);
  assert.equal(await dispatchPersonalReminders(),1);
  assert.equal((await request('viewer','/reminders')).data.data.find(reminder=>reminder.id===created.data.data.id).status,'sent');
});
