const service=require('../services/notificationService');
const {updatePreferencesSchema}=require('../../shared/validation/notificationSchemas');
const integer=(value,fallback,min,max)=>{const n=value===undefined?fallback:Number(value);if(!Number.isSafeInteger(n)||n<min||n>max)throw Object.assign(new Error('Invalid pagination value.'),{statusCode:400});return n;};
exports.getNotifications=async(req,res,next)=>{try{res.json({success:true,data:await service.getUserNotifications(req.user.id,integer(req.query.limit,50,1,100),integer(req.query.offset,0,0,1000000))});}catch(error){next(error);}};
exports.getUnreadCount=async(req,res,next)=>{try{res.json({success:true,data:{count:await service.getUnreadCount(req.user.id)}});}catch(error){next(error);}};
exports.markAsRead=async(req,res,next)=>{try{const id=integer(req.params.id,0,1,Number.MAX_SAFE_INTEGER);if(!await service.markAsRead(req.user.id,id))return res.status(404).json({success:false,message:'Notification not found.'});res.json({success:true,message:'Notification marked as read'});}catch(error){next(error);}};
exports.markAllAsRead=async(req,res,next)=>{try{await service.markAllAsRead(req.user.id);res.json({success:true,message:'All notifications marked as read'});}catch(error){next(error);}};
exports.getPreferences=async(req,res,next)=>{try{res.json({success:true,data:await service.getPreferences(req.user.id)});}catch(error){next(error);}};
exports.updatePreferences=async(req,res,next)=>{try{const result=updatePreferencesSchema.safeParse(req.body);if(!result.success)return res.status(400).json({success:false,message:'Invalid notification preferences',errors:result.error.issues.map(issue=>({path:issue.path,message:issue.message}))});await service.updatePreferences(req.user.id,result.data);res.json({success:true,message:'Preferences updated successfully'});}catch(error){next(error);}};

const push=require('../services/mobilePushService');
const {pushDeviceSchema,removePushDeviceSchema}=require('../../shared/validation/notificationSchemas');
exports.registerPushDevice=async(req,res,next)=>{try{const result=pushDeviceSchema.safeParse(req.body);if(!result.success)return res.status(400).json({success:false,message:'Invalid push device.'});if(!push.enabled())return res.status(503).json({success:false,message:'Mobile push is not enabled on this server.'});await push.registerDevice(req.user.id,result.data);res.json({success:true,message:'Push device registered.'});}catch(error){next(error);}};
exports.removePushDevice=async(req,res,next)=>{try{const result=removePushDeviceSchema.safeParse(req.body);if(!result.success)return res.status(400).json({success:false,message:'Invalid push device.'});await push.removeDevice(req.user.id,result.data.token);res.json({success:true,message:'Push device removed.'});}catch(error){next(error);}};
