import { z } from 'zod';
import { TASK_STATUS_VALUES } from '../constants/taskStatus.js';
import { TASK_PRIORITY_VALUES } from '../constants/taskPriority.js';
import { optionalDate,descriptionField,identifier } from './fields.js';
const fields={name:z.string().trim().min(1).max(255),description:descriptionField,status:z.enum(TASK_STATUS_VALUES),priority:z.enum(TASK_PRIORITY_VALUES),assigned_to:identifier.nullable().optional(),due_date:optionalDate};
export const createTaskSchema=z.object({...fields,project_id:identifier,status:fields.status.default('Pending'),priority:fields.priority.default('Medium')}).strict();
export const updateTaskSchema=z.object(fields).partial().strict();
export const updateTaskStatusSchema=z.object({status:fields.status}).strict();
export const assignTaskSchema=z.object({assigned_to:identifier.nullable()}).strict();
export default {createTaskSchema,updateTaskSchema,updateTaskStatusSchema,assignTaskSchema};
